# Generated by Django 3.2.4 on 2021-06-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='john', max_length=100),
        ),
    ]
