# Generated by Django 3.2.4 on 2021-06-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='john', max_length=100, unique=True),
        ),
    ]
